spring:
  application:
    name: rabbitmq-hello

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-returns: true #开启确认消息是否到达交换器
    publisher-confirms: true #开启确认消息是否到达队列
    listener:
      simple:
        concurrency: 2 #指定最小的消费者数量.
        max-concurrency: 2 #指定最大的消费者数量.
        acknowledge-mode: auto #开启ack
      direct:
        acknowledge-mode: auto #开启ack
    template:
      mandatory: true #支持消息的确认与返回